AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create an EC2 instance'

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
  KeyName:
    Type: AWS::EC2::KeyPair::miles
    Description: Name of an existing EC2 KeyPair to enable SSH access
    Default: my-key-pair
  AMIId:
    Type: String
    Description: AMI ID for the EC2 instance
    Default: ami-0ce8c2b29fcc8a346  # Example AMI (Amazon Linux 2, us-east-1)
  SecurityGroup:
    Type: String
    Description: Security Group ID
    Default: sg-030401d854e284ecf  # Example Security Group ID

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref AMIId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: MyEC2Instance
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 8
            VolumeType: gp2

Outputs:
  InstanceId:
    Description: ID of the created EC2 instance
    Value: !Ref MyEC2Instance
  PublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt MyEC2Instance.PublicIp