AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create an EC2 instance'

Resources:
MyEC2Instance:
Type: 'AWS::EC2::Instance'
Properties:
ImageId: aami-0ce8c2b29fcc8a346
InstanceType: t2.mico
SecurityGroupIds:
- sg-030401d854e284ecf
